baseURL = "/"
languageCode = "en-us"
title = "badstreff"


[module]
  [module.hugoVersion]
    extended=true
    min = "0.41.0"
  [[module.imports]]
    disable = false
    ignoreConfig = false
    ignoreImports = false
  # [[module.imports]]
  #   path = 'github.com/hanwenguo/hugo-theme-nostyleplease'
  #   disable = false


[privacy]
  [privacy.disqus]
    disable = false
[services]
  [services.disqus]
    shortname = 'badstreff'


[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'rrt'
    tabWidth = 4
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
    ordered = false

[params]
  [params.theme_config]
    appearance = "auto"
    back_home_text = ".."
    date_format = "2006-01-02"
    isListGroupByDate = false
